### ISSUE TITLE
Level 3 categories

### ISSUE THREAD

**Issue by cord** [tanmuhittin/nova-collapsible-groups#1]
Good stuff!

would be great to have a 3 level navigation structure like this:

![](http://element.eleme.io/static/navbar_3.8dcec92.png)

**Comment by tanmuhittin** [comment]
This requires to add a subGroup option to the resources and implementation of this feature in navigation blade file or "grouped-resource-collapsible" vue component. This is doable. But I think Nova needs a menu builder like a CMS. https://github.com/laravel/nova-issues/issues/2
