### ISSUE TITLE
Clicking on group closes responsive sidebar

### ISSUE THREAD

**Issue by njsoria** [tanmuhittin/nova-collapsible-groups#2]
"gregoriohc/laravel-nova-theme-responsive": "^0.6.1",

Is there anyway to stop this from happening? When combining this package with the responsive package above, clicking on a group closes the collapsible navigation panel.

Thanks!

**Comment by tanmuhittin** [comment]
Thanks for the feedback. I prepared a fix for that. Please verify fix works using dev master branch 😄  👍

**Comment by njsoria** [comment]
perfect! Thanks for the quick fix. Keep my employer happy :)

**Comment by rjacobsen2012** [comment]
> Thanks for the feedback. I prepared a fix for that. Please verify fix works using dev master branch 😄 👍

@tanmuhittin Can you create a new stable release for this?
