### ISSUE TITLE
Add Collapsible Indicator

### ISSUE THREAD

**Issue by njsoria** [tanmuhittin/nova-collapsible-groups#4]
Hi there!

I was trying to add an indicator to the right of the $group header to show if we're collapsed or not. It makes the interface more intuitive for someone who's not as familiar with the software.

A simple + or -

Is this something you can implement or provide an option for? Also being able to default to expanded or collapsed would be a nice touch. If you could suggest how to accomplish this or tweak the package.

Thanks!

**Comment by vesper8** [comment]
I agree having a small caret to indicate that the item can be expanded/collapsed is needed to guide users that are new to the admin panel

It would also be very nice if there was a way to define which groups start collapsed and which start expanded

any chance you could create an update with these features please @tanmuhittin ?

**Comment by tanmuhittin** [comment]
#5
